# This is a starter workflow to help you get started with publishing Dependabot Alerts to Confluence using Actions

# Required Secrets:
# sphinx_confluence_space
# sphinx_srvc_user
# sphinx_srvc_key

# Optional Secrets:
# sphinx_parent_page

name: DependAlert User
on: [pull_request]

jobs:
  call-workflow-in-another-repo:
    if: ${{ github.actor == "dependabot[bot]" }}

    uses: oneTakeda/devops-dependabot-action/.github/workflows/dependalert.yaml@0.6b1
    with:
        sphinx_confluence_space: "YOURSPACE"
        sphinx_srvc_user: "you@takeda.com"
        # sphinx_parent_page: "Confluence Parent Page"   # OPTIONAL
        # alerts_title_override: "Sample Page Title"     # OPTIONAL
    secrets:
        gh_app_id: ${{ secrets.DEPEND_ALERT_GH_APP_ID }}
        gh_app_key: ${{ secrets.DEPEND_ALERT_GH_APP_PRIVATE_KEY }}
        sphinx_srvc_key: ${{ secrets.SPHINX_SRVC_KEY }}   # atlassian key for you@takeda.com
