# This is a starter workflow to help you get started with publishing Dependabot Alerts to Confluence using Actions

# Required Inputs:
# build
# sphinx_confluence_space
# sphinx_srvc_user
# sphinx_parent_page

# Required Secrets:
# sphinx_srvc_key
# gh_app_id (org secret)
# gh_app_key (org secret)

name: DependAlert User
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allows for manual runs from the UI and CLI - optional]
jobs:
  call-workflow-in-another-repo:
    if: ${{ github.actor == 'dependabot[bot]' }}

    uses: oneTakeda/devops-dependabot-action/.github/workflows/dependalert.yaml@0.8b1
    with:
        build: "0.8b1"
        sphinx_confluence_space: "YOURSPACE"
        sphinx_srvc_user: "first.last@takeda.com"
        sphinx_parent_page: "12345678"  
    secrets:
        gh_app_id: ${{ secrets.DEPEND_ALERT_GH_APP_ID }}
        gh_app_key: ${{ secrets.DEPEND_ALERT_GH_APP_PRIVATE_KEY }}
        sphinx_srvc_key: ${{ secrets.SPHINX_SRVC_KEY }}  
